### ISSUE TITLE
Map overlaps the other components 

### ISSUE THREAD

**Issue by ClydeCorrea** [capacitor-community/capacitor-googlemaps-native#120] opened 2021-11-26 17:44 UTC
Map overlaps the components like spinners and drawers when used in ionic 5 capacitor in angular

**Comment by DwieDima** [comment] 2021-11-30 15:18
#84

**Comment by tafelnl** [comment] 2022-02-12 12:12
closing as duplicate of #84

**Closed by tafelnl** 2022-02-12 12:12 UTC
